FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./

# Instala as dependências do projeto e o nodemon globalmente
RUN npm install --force

COPY . .

EXPOSE 3333

CMD [ "npm", "run", "dev" ]